#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_FOV 60
#define CONFIG_NPLANE 0.01
#define CONFIG_FPLANE 50.0
#define CONFIG_FRAMEDELAY 12
#define CONFIG_TERRAIN_DETAIL 4.0
#define CONFIG_RENDER_DETAIL 30
#define CONFIG_TREE_H 1.50
#define CONFIG_TREE_R 0.25

#define CONFIG_TREE_DETAIL CONFIG_RENDER_DETAIL
#define CONFIG_MOVE_SPEED 0.06
#define CONFIG_SUN_RADIUS 10
#define CONFIG_SUN_DIST 100
#define CONFIG_SUN_DIST2 (CONFIG_SUN_DIST * CONFIG_SUN_DIST)
#define CONFIG_SUN_COLOR3F 1, 1, 0
#define CONFIG_MAXTIME 1000000.0
#define CONFIG_WINDOW_W 480
#define CONFIG_WINDOW_H 360
#define CONFIG_AVATAR_HEIGHT 0.3

#endif /* CONFIG_H */
