#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_FOV 60
#define CONFIG_NPLANE 0.01
#define CONFIG_FPLANE 1000.0
#define CONFIG_FRAMEDELAY 12
#define CONFIG_RENDER_DETAIL 64
#define CONFIG_BEZIER_DETAIL 4
#define CONFIG_TREE_H 1.50
#define CONFIG_TREE_R 0.25
#define CONFIG_NSTAR 1000
#define CONFIG_RAIN_RADIUS 16
#define CONFIG_RAIN_DENSITY 32
#define CONFIG_MOVE_SPEED 0.06
#define CONFIG_SUN_RADIUS 10
#define CONFIG_WINDOW_W 480
#define CONFIG_WINDOW_H 360
#define CONFIG_ROTATION_SPEED 0.2
#define CONFIG_AVATAR_HEIGHT 0.3

#endif /* CONFIG_H */
